# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20151215_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_ts',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2015, 12, 15, 20, 38, 25, 945521, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
