# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_basketproduct_order_orderproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField()),
                ('creation_ts', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='basketproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.SessionBasket'),
            preserve_default=False,
        ),
    ]
